export const skillGroups = [
  {
    title: "Product Engineering",
    items: [
      "TypeScript",
      "React",
      "Next.js",
      "Design Systems",
      "UX Engineering",
      "Web Performance",
      "Accessibility",
      "Progressive Web Apps",
    ],
  },
  {
    title: "Back-end Engineering",
    items: [
      "Node.js",
      "REST APIs",
      "GraphQL",
      "PostgreSQL",
      "Redis",
      "Authentication",
      "Background Jobs",
      "API Design",
    ],
  },
  {
    title: "Software Architecture",
    items: [
      "System Design",
      "Domain-Driven Design",
      "Clean Architecture",
      "Event-Driven Architecture",
      "Scalability",
      "Observability",
      "Technical Documentation",
      "Technical Specifications",
    ],
  },
  {
    title: "Engineering Practices",
    items: [
      "Spec-Driven Development",
      "Test-Driven Development",
      "Automated Testing",
      "End-to-End Testing",
      "Refactoring",
      "Code Review",
      "Continuous Integration",
      "Continuous Delivery",
      "Extreme Programming",
    ],
  },
  {
    title: "Cloud and DevOps",
    items: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Serverless",
      "S3",
      "RDS",
      "Cloud Functions",
      "Infrastructure as Code",
      "DNS",
    ],
  },
  {
    title: "AI-assisted Development",
    items: [
      "LLM Orchestration",
      "AI Coding Agents",
      "Agentic Workflows",
      "AGENTS.md",
      "Sub-agents",
      "Prompt Engineering",
      "AI-assisted Testing",
      "AI-assisted Documentation",
    ],
  },
] as const;
